name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t qr-code-generator-app .

      - name: Run QR code generator
        run: |
          docker run --name qr-generator \
            qr-code-generator-app \
            --url https://www.njit.edu

      - name: Display container logs
        run: docker logs qr-generator